let money = 1e5;
let income = 5000;
let addExpenses = 'ТРЕНАЖЕРНЫЙ зал, ресторан, транспорт';
let deposit = true;
let mission = 1e6;
let period = 12;
console.log(typeof(money));
console.log(typeof(income));
console.log(typeof(deposit));
console.log(addExpenses.length);
console.log('Период равен ' + period + ' месяцев' );
console.log(addExpenses.toLowerCase());
let budgetDay = money / 30;
console.log(budgetDay);